plow-technologies/inferno

- flake.lock
- flake.nix
- inferno-lsp/app/Main.hs
- inferno-lsp/inferno-lsp.cabal
- inferno-lsp/src/Inferno/LSP/ParseInfer.hs
- inferno-lsp/src/Inferno/LSP/Server.hs
- vscode-inferno-lsp-server/package-lock.json
- vscode-inferno-lsp-server/package.json
The nix build of the VS code inferno LSP extension was broken.
This also re-introduces the LSP server binary and re-routes the logging back to stderr, since the server communicates via stdio with the VS Code extension. 
Finally, this also includes some M1 specific tweaks due to some broken packages:
- ormolu is broken on the M1, failing with a segfault when linking the executable
- `ghc884` is not supported on the M1, the earliest supported one being `ghc8107`
> Fix broken vs code extension build + lsp server

- .gitignore
- flake.nix
- vscode-inferno-lsp-server/LICENSE
- vscode-inferno-lsp-server/package.json
- vscode-inferno-syntax-highlighting/.gitignore
- vscode-inferno-syntax-highlighting/LICENSE
- vscode-inferno-syntax-highlighting/package-lock.json
- vscode-inferno-syntax-highlighting/package.json
Closes #15
The package's `npmBuild` calls `vsce`, but this was removed from the `buildInputs` in a previous PR. The `@vscode/vsce` dependency was also missing from `package.json`
> Fix `packages.vscode-inferno-syntax-highlighting`

- flake.lock
- flake.nix
- inferno-types/inferno-types.cabal
This adds a profiling build of the inferno binary, which can be used via
```
nix shell .#inferno-core:exe:inferno-ghc924-prof
```
However, I've had to update `haskell.nix`, as the profiling build needs `recursion-schemes` >=5.2.2.3, due to:
> Workaround for https://gitlab.haskell.org/ghc/ghc/-/issues/18320, which was preventing code calling makeBaseFunctor from being profiled. 
The update to `haskell.nix` seems to have broken the dev shell??
> Profiling build of `inferno` binary

- inferno-core/inferno-core.cabal
- inferno-types/inferno-types.cabal
- inferno-vc/src/Inferno/VersionControl/Operations.hs
#20 updated the version of `recursion-schemes` in `inferno-types.cabal`, but this conflicts with the version picked by `inferno-core.cabal` by my HLS:
```
2023-01-12 06:22:17.2560000 [client] ERROR Error: haskell-language-server --project-ghc-version exited with exit code 1:
Failed to find the GHC version of this Cabal project.
Error when calling cabal exec -v0 -- ghc --print-libdir
cabal: Could not resolve dependencies:
[__0] trying: inferno-core-0.1.0.3 (user goal)
[__1] trying: recursion-schemes-5.2.2.2 (dependency of inferno-core)
[__2] next goal: inferno-types (user goal)
[__2] rejecting: inferno-types-0.1.0.0 (conflict: recursion-schemes==5.2.2.2,
inferno-types => recursion-schemes>=5.2.2.3 && <5.3)
[__2] fail (backjumping, conflict set: inferno-types, recursion-schemes)
After …
```
> Fix dependency version conflict

- inferno-core/CHANGELOG.md
- inferno-core/inferno-core.cabal
- inferno-core/src/Inferno/Parse.hs
- inferno-core/test/Eval/Spec.hs
This PR improves the speed of parsing parenthesised expressions. For example:
```
let x = ((((((((2)))))))) in x + 1
```
currently takes 30s to parse! This PR refactors parsing of tuples and prefix ops so that the parser does less backtracking, and parses the example in 0.1s.
> [perf] Refactor parsing of tuples and prefix ops

- inferno-core/src/Inferno/Instances/Arbitrary.hs
Issue:
Trying to use Inferno in our internal repo:
```
src/Inferno/Instances/Arbitrary.hs:79:5: error:
Module ‘Test.QuickCheck’ does not export ‘chooseInt’
|
79 |     chooseInt,
|     ^^^^^^^^^
[19 of 19] Compiling Inferno.Utils.QQ.Script ( src/Inferno/Utils/QQ/Script.hs, dist/build/Inferno/Utils/QQ/Script.o )
error: builder for '/nix/store/g05v588giyqmlhsc0lrdw4iir9sasyfa-inferno-core-lib-inferno-core-0.1.2.drv' failed with exit code 1;
last 10 log lines:
> [16 of 19] Compiling Inferno.Utils.QQ.Module ( src/Inferno/Utils/QQ/Module.hs, dist/build/Inferno/Utils/QQ/Module.o )
> [17 of 19] Compiling Inferno.Module.Prelude ( src/Inferno/Module/Prelude.hs, dist/build/Inferno/Module/Prelude.o )
> [18 of 19] Compiling Inferno.Instances.Arbitrary ( src/Inferno/Instances/Arbitrary.hs, …
```
> Revert usage of chooseInt (not supported on old Quickcheck versions)

- inferno-core/CHANGELOG.md
- inferno-core/app/Main.hs
- inferno-core/inferno-core.cabal
- inferno-core/src/Inferno/Eval.hs
- inferno-core/src/Inferno/Eval/Error.hs
- inferno-core/src/Inferno/Instances/Arbitrary.hs
- inferno-core/src/Inferno/Module.hs
- inferno-core/src/Inferno/Module/Cast.hs
- inferno-core/src/Inferno/Module/Prelude.hs
- inferno-core/src/Inferno/Module/Prelude/Defs.hs
- inferno-core/src/Inferno/Utils/QQ/Script.hs
- inferno-core/test/Utils.hs
- inferno-lsp/CHANGELOG.md
- inferno-lsp/app/Main.hs
- inferno-lsp/inferno-lsp.cabal
- inferno-lsp/src/Inferno/LSP/Completion.hs
- inferno-lsp/src/Inferno/LSP/ParseInfer.hs
- inferno-lsp/src/Inferno/LSP/Server.hs
- inferno-types/CHANGELOG.md
- inferno-types/inferno-types.cabal
- inferno-types/src/Inferno/Types/Value.hs
- inferno-vc/CHANGELOG.md
This PR adds IO to the monad stack of the inferno interpreter. This is needed to have primitives whose implementations perform IO actions, e.g., impure random number generation. This will also be used by the ML primitives that call out to torch.
> Add MonadIO to prelude and monad stack to allow random primitive

- inferno-lsp/CHANGELOG.md
- inferno-lsp/inferno-lsp.cabal
- inferno-lsp/src/Inferno/LSP/ParseInfer.hs
I added a check in the LSP that checks if the script type returns a function (by checking if it expects more inputs than input parameters supplied). This should warn users and make it less likely that they confuse the input parameters that are selected in the frontend UI with the parameters of a lambda function.
> LSP: error if script evaluates to a function

- inferno-lsp/CHANGELOG.md
- inferno-lsp/inferno-lsp.cabal
- inferno-lsp/src/Inferno/LSP/Server.hs
This PR adds a timeout to the LSP so that if parsing or type checking hangs/takes too long, the editor doesn't break too. A timeout results in an error diagnostic, so that if the user modifies the script, the LSP can process the new version:
(This example takes too long to parse, see #51 )
> Add a timeout to LSP's parseAndInfer

- .github/workflows/build.yml
- README.md
- flake.nix
- nix/default.nix
Closes #25 
I'd like to do this for a few reason:
- `haskell-language-server` integration is currently broken, this fixes that
- we're planning GHC upgrades elsewhere, it's a good idea to do this incrementally, especially considering our recent Hasktorch integration
- using `cabal repl` with GHC 9.2.4 (which is my primary development mode) has an irritating bug where auto-completing any module name leads to a compiler panic
Note: I haven't changed anything else regarding e.g. the `index-state`, so we're still using the same dependencies. The only other change is that now some of the flake outputs are suffixed with `-ghc925` instead of `-ghc924`
> Upgrade to GHC 9.2.5

- flake.nix
Since merging the GHC upgrade it seems that HLS gets rebuilt on every CI run. We don't actually need to have the dev shell built and it appears to be working locally, so we can disable it for the time being while I investigate
> Don't build `devShells..default`

- .github/torch.sh
- .github/workflows/build.yml
- README.md
- flake.lock
- flake.nix
Closes #65. Previously `devShells..pytorch` was using an incorrect version (one major version too high). I added something to the docs mentioning `devShells..pytorch` and also used it to run the MNIST example on CI. This way we will always be using the same version everywhere. I temporarily modified the workflow file in order to ignore the cache and ran the CI job manually and it worked (otherwise that part wouldn't run because it's been cached)
> Fix `torch` versions, document, use on CI

- cabal.project
- nix/default.nix
This removes the awful hack I originally implemented to get the conditional import in the `cabal.project` working with haskell.nix. The GHC 9 config is still read in conditionally in the haskell.nix setup, but I removed it from the main `cabal.project` (so it doesn't need to be removed when building with Nix as before)
For building outside of Nix, the `shellHook` in `devShells..default` now generates a `cabal.project.local` with the `import` stanza (but it won't overwrite an existing file). This is nice because it can imported using an absolute path this, which wasn't possible before, so Cabal and HLS will actually work now if invoked from a different directory than the project root
> Generate `cabal.project.local` in the `shellHook`

- inferno-lsp/CHANGELOG.md
- inferno-lsp/inferno-lsp.cabal
- inferno-lsp/src/Inferno/LSP/ParseInfer.hs
- inferno-types/CHANGELOG.md
- inferno-types/inferno-types.cabal
- inferno-types/src/Inferno/Types/Syntax.hs
A script like `"foo" // bar` with input parameter `input0` was being saved by LSP as `CommentAfter(... Lam(...))` which broke `extractArgsAndPrettyPrint`, which expects it to look like `Lam(...)`.
This PR ensures that the LSP returns an Expr that has Lam as the outermost constructor.
> Ensure scripts are Lam(...) and better error message when not

- inferno-vc/inferno-vc.cabal
- inferno-vc/src/Inferno/VersionControl/Client/Cached.hs
- inferno-vc/src/Inferno/VersionControl/Log.hs
- inferno-vc/src/Inferno/VersionControl/Operations.hs
- inferno-vc/src/Inferno/VersionControl/Operations/Filesystem.hs
- inferno-vc/src/Inferno/VersionControl/Server.hs
- inferno-vc/src/Inferno/VersionControl/Server/Types.hs
- inferno-vc/src/Inferno/VersionControl/Testing.hs
- inferno-vc/test/Spec.hs
Refactors `Inferno.VersionControl.Operations` into a type-class, moving the existing implementation to an instance in `Inferno.VersionControl.Operations.Filesystem`.
No behavior-modifying changes should have been introduced except using `atomicWriteFile` (from `atomic-write`) in `Inferno.VersionControl.Client.Cached` because it looks like it can help avoiding corruption if two threads are caching the same deps file concurrently.
> Pluggable storage backend

- inferno-vc/src/Inferno/VersionControl/Operations.hs
- inferno-vc/src/Inferno/VersionControl/Operations/Filesystem.hs
- inferno-vc/src/Inferno/VersionControl/Server.hs
- inferno-vc/src/Inferno/VersionControl/Testing.hs
- inferno-vc/test/Spec.hs
Also removed `getAllHeads` and added `deleteAutosavedVCObjectsOlderThan` instead to allow for more efficient implementations.
The changes to the class that make the usage simpler are:
- Removed the `De/Serializable` associated constraints which were applied on the `group` and `author` type variables of `VCMeta` and added a `Group` and `Author` associated types instead. See the changes in `runServer` and `runServerConfig` call sites.
This change is not only cosmetic, it also gives knowledge of `author` and `group` to all type-class method which can use it to deserialise stuff without resorting to AmbiguousTypes or Proxies (which moves the burden of keeping track of the type witnesses to the call-sites)
- Made the constraint `AsType err VCStoreError` that `runServer/Config` requires …
> [inferno-vc] Simplified InfernoVCOperations typeclass usage

- .github/workflows/build.yml
I was working on an ad-hoc solution for #78 and then I found that there's an existing GH action that does basically the same thing. I've triggered several (expected) rebuilds on a different branch with the same actions config and haven't experienced any rebuilds of dependencies. It appears to work fine with Cachix as well
One advantage to also using this is that if an external contributor ever wanted to open a PR, the Cachix cache wouldn't work because it always requires a secret, which are unavailable for PRs from forks
Note that the `magic-cache-action` uses the built-in GH cache as a substituter (rather than mounting a cache as the Nix store), so dependencies will still be downloaded in any event
> Add magic cache

- inferno-core/CHANGELOG.md
- inferno-core/inferno-core.cabal
- inferno-core/src/Inferno/Module/Prelude.hs
- inferno-core/src/Inferno/Module/Prelude/Defs.hs
- inferno-core/test/Eval/Spec.hs
This reverts commit a164c3e3c58b16f4e05037fbe1b360be9cf0a0d1 until we can figure out how to share the prelude evaluation in downstream users of Inferno.
> Revert "Add some primitives; speed up tests (#81)"

- inferno-core/CHANGELOG.md
- inferno-core/app/Main.hs
- inferno-core/inferno-core.cabal
- inferno-core/src/Inferno/Core.hs
- inferno-core/src/Inferno/Eval.hs
- inferno-core/test/Eval/Spec.hs
- inferno-core/test/Infer/Spec.hs
- inferno-lsp/CHANGELOG.md
- inferno-lsp/inferno-lsp.cabal
- inferno-ml-remote/CHANGELOG.md
- inferno-ml-remote/inferno-ml-remote.cabal
- inferno-ml-remote/src/Inferno/ML/Remote/Handler.hs
- inferno-ml-remote/src/Inferno/ML/Remote/Server.hs
- inferno-ml-remote/src/Inferno/ML/Remote/Utils.hs
- inferno-ml-remote/test/Main.hs
- inferno-ml/CHANGELOG.md
- inferno-ml/app/Main.hs
- inferno-ml/inferno-ml.cabal
- inferno-ml/test/Spec.hs
- inferno-types/CHANGELOG.md
- inferno-types/inferno-types.cabal
- inferno-types/src/Inferno/Types/Value.hs
This PR generalizes the `Interpreter` API to run in a user supplied monad `m` instead of `IO`. This can be used to run the interpreter in some context, see the `inferno-core/test/Eval/Spec.hs` test for an example.
> Run Interpreter in custom monad `m`

- inferno-core/CHANGELOG.md
- inferno-core/inferno-core.cabal
- inferno-core/src/Inferno/Module/Prelude.hs
- inferno-core/src/Inferno/Module/Prelude/Defs.hs
- inferno-core/test/Eval/Spec.hs
This PR adds some (long awaited) primitives to Inferno, again. :)
See #81 #84 
```ocaml
// Function composition with `<<`, `.` creates parsing issues
assert Array.map ((Text.append "a") << (Text.append "b")) ["0", "1"] == ["ab0", "ab1"] in
// Pipe operator `|>`
assert "0" |> Text.append "a" |> Text.append "b" == "ba0" in
// Some tuple stuff:
assert fst (1, 0) == snd (0, 1) in
assert zip [1, 2, 3] [4, 5] == [(1, 4), (2, 5)] in
assert zip [1, 2] ["a", "b"] == [(1,"a"),(2,"b")] in
assert zip [1] ["a", "b"] == [(1,"a")] in
assert zip [1, 2] ["a"] == [(1,"a")] in
assert zip [] [1, 2] == [] in
assert zip [1, 2] [] == [] in
0
```
> Add some tuple and fn comp primitives again

- inferno-core/CHANGELOG.md
- inferno-core/inferno-core.cabal
- inferno-core/src/Inferno/Module/Prelude.hs
- inferno-core/src/Inferno/Module/Prelude/Defs.hs
- inferno-core/test/Eval/Spec.hs
- inferno-lsp/CHANGELOG.md
- inferno-lsp/inferno-lsp.cabal
This PR makes the following Array functions total by returning `option` values instead of throwing runtime errors when the input array is empty:
`minimum, maximum, average, argmin, argmax`
> Make some Array functions total by returning options

- inferno-core/CHANGELOG.md
- inferno-core/app/Main.hs
- inferno-core/inferno-core.cabal
- inferno-core/src/Inferno/Core.hs
- inferno-core/src/Inferno/Eval.hs
- inferno-core/src/Inferno/Module.hs
- inferno-core/src/Inferno/Module/Cast.hs
- inferno-core/src/Inferno/Module/Prelude.hs
- inferno-core/src/Inferno/Utils/QQ/Module.hs
- inferno-lsp/CHANGELOG.md
- inferno-lsp/inferno-lsp.cabal
- inferno-ml/CHANGELOG.md
- inferno-ml/inferno-ml.cabal
- inferno-ml/src/Inferno/ML/Module/Prelude.hs
- inferno-ml/src/Inferno/ML/Types/Value.hs
This PR aims to reduce the memory consumption of inferno, by storing prelude functions that are defined as inferno `Expr`s as `Expr`s in the prelude and not evaluating the expressions until runtime. You can think of this as though we're inlining any such primitives to the script.
Because of this, prelude evaluation no longer needs to be within the `ImplEnvM` monad, so that has been removed as well. This has meant we changed the type of `toValue` to no longer be under a monad too.
This should reduce the memory consumption significantly, but might increase runtime slightly. I don't expect the increase to be too much because most primitive definitions are functions, so they can't be fully evaluated at compile time anyway, which is why they were being stored in memory as huge thunks.
> Defer evaluating prelude expr defs until runtime

- inferno-ml-server-types/CHANGELOG.md
- inferno-ml-server-types/inferno-ml-server-types.cabal
- inferno-ml-server-types/src/Inferno/ML/Server/Types.hs
Splits the `Model` type into two parts:
- `Model`, which now just contains metadata that should not change between versions (`name`, `user`, `permissions`)
- `ModelVersion`, which contains other version-specific metadata as well as the actual model contents
Splitting the type like this helps prevent certain undesirable scenarios. For example, all model versions previously had their own `permissions`. This meant that it would be possible for a user to have access to (or even own) one version of a model, but not others. That's not what we want. 
Also, previously the different versions of a model were only linked together by their `name` field. This wasn't really structured into the database in any way. Now it is possible to get all versions of a model directly by a foreign key lookup.
I've …
> [inferno-ml-server-types] Split `Model` and `ModelVersion`

- inferno-core/CHANGELOG.md
- inferno-core/inferno-core.cabal
- inferno-core/src/Inferno/Eval.hs
- inferno-core/src/Inferno/Infer.hs
- inferno-core/src/Inferno/Infer/Error.hs
- inferno-core/src/Inferno/Infer/Exhaustiveness.hs
- inferno-core/src/Inferno/Infer/Pinned.hs
- inferno-core/src/Inferno/Instances/Arbitrary.hs
- inferno-core/src/Inferno/Parse.hs
- inferno-core/src/Inferno/Parse/Commented.hs
- inferno-core/test/Eval/Spec.hs
- inferno-core/test/Infer/Spec.hs
- inferno-core/test/Parse/Spec.hs
- inferno-lsp/CHANGELOG.md
- inferno-lsp/inferno-lsp.cabal
- inferno-lsp/src/Inferno/LSP/ParseInfer.hs
- inferno-types/CHANGELOG.md
- inferno-types/inferno-types.cabal
- inferno-types/src/Inferno/Types/Syntax.hs
This PR follows up on #103 by adding pattern matching for records. E.g.
```ocaml
let f = fun r -> match r with { | {x = x; y = y} -> x + y } in f {x = 3.3; y = 5.1}
```
It also adds a type error when record literals or patterns use duplicate field names.
> Add pattern matching for records

- inferno-core/CHANGELOG.md
- inferno-core/inferno-core.cabal
- inferno-core/src/Inferno/Docs.hs
- inferno-core/src/Inferno/Module/Prelude.hs
This PR adds Inferno language reference to a new module `Inferno.Docs` so that it can be combined with auto-generated docstrings and generate a comprehensive documentation for Inferno.
> Add documentation and language reference

- inferno-ml-server-types/CHANGELOG.md
- inferno-ml-server-types/inferno-ml-server-types.cabal
- inferno-ml-server-types/src/Inferno/ML/Server/Client.hs
- inferno-ml-server-types/src/Inferno/ML/Server/Types.hs
- inferno-ml-server/CHANGELOG.md
- inferno-ml-server/exe/Client.hs
- inferno-ml-server/inferno-ml-server.cabal
- inferno-ml-server/src/Inferno/ML/Server/Inference.hs
- inferno-ml-server/src/Inferno/ML/Server/Types.hs
- inferno-ml-server/src/Inferno/ML/Server/Utils.hs
- nix/inferno-ml/migrations/v1-create-tables.sql
Adds support for getting total elapsed time, CPU time, and memory allocations every time an inference param is run in `inferno-ml-server`
Originally I thought we could use EKG for this, but then we would need to keep `inferno-ml-server` on to get the evaluation info. Given our constraints elsewhere, we should avoid this. So I've continued my quest to Use Postgres For Everything™ and stored it in the DB
> [inferno-ml] Save evaluation info

- inferno-ml-server-types/CHANGELOG.md
- inferno-ml-server-types/inferno-ml-server-types.cabal
- inferno-ml-server-types/src/Inferno/ML/Server/Client.hs
- inferno-ml-server-types/src/Inferno/ML/Server/Types.hs
- inferno-ml-server/CHANGELOG.md
- inferno-ml-server/exe/ParseAndSave.hs
- inferno-ml-server/inferno-ml-server.cabal
- inferno-ml-server/src/Inferno/ML/Server/Inference.hs
- inferno-ml-server/src/Inferno/ML/Server/Module/Bridge.hs
- inferno-ml-server/src/Inferno/ML/Server/Types.hs
- nix/inferno-ml/migrations/v1-create-tables.sql
Adds a `resolution` field to the inference param type. The script evaluator will use this resolution as part of the implicit env, unless the optional `res` query param is set via the `/inference` route. Originally I was going to drop that query param, but then I thought it would be useful to allow overriding `?resolution` without needing to edit the param or the script
> [inferno-ml] Add `resolution` to inference params

- inferno-ml-server-types/CHANGELOG.md
- inferno-ml-server-types/inferno-ml-server-types.cabal
- inferno-ml-server-types/src/Inferno/ML/Server/Types.hs
- inferno-ml-server/CHANGELOG.md
- inferno-ml-server/exe/ParseAndSave.hs
- inferno-ml-server/inferno-ml-server.cabal
- inferno-ml-server/src/Inferno/ML/Server.hs
- inferno-ml-server/src/Inferno/ML/Server/Bridge.hs
- inferno-ml-server/src/Inferno/ML/Server/Inference.hs
- inferno-ml-server/src/Inferno/ML/Server/Inference/Model.hs
- inferno-ml-server/src/Inferno/ML/Server/Log.hs
- inferno-ml-server/src/Inferno/ML/Server/Types.hs
- inferno-ml-server/test/Main.hs
- nix/inferno-ml/migrations/v1-create-tables.sql
- nix/inferno-ml/tests/server.nix
Adds the ability to link multiple `ModelVersion` IDs to inference params and updates `inferno-ml-server` script evaluator to copy all models linked to a given param
Also adds configurable log level for `inferno-ml-server`
> [inferno-ml] Link multiple models to params

- docs/dev.md
- inferno-ml-server-types/CHANGELOG.md
- inferno-ml-server-types/inferno-ml-server-types.cabal
- inferno-ml-server-types/src/Inferno/ML/Server/Types.hs
- inferno-ml-server/CHANGELOG.md
- inferno-ml-server/exe/ParseAndSave.hs
- inferno-ml-server/inferno-ml-server.cabal
- inferno-ml-server/src/Inferno/ML/Server/Inference.hs
- inferno-ml-server/src/Inferno/ML/Server/Types.hs
- inferno-ml-server/test/Main.hs
- inferno-ml/CHANGELOG.md
- inferno-ml/inferno-ml.cabal
- inferno-ml/src/Inferno/ML/Module/Prelude.hs
- inferno-ml/src/Inferno/ML/Types/Value.hs
- inferno-ml/test/downhole-autoencoder.inferno
- inferno-ml/test/mnist.inferno
- nix/inferno-ml/migrations/v1-create-tables.sql
- nix/inferno-ml/tests/scripts/contrived.inferno
- nix/inferno-ml/tests/scripts/mnist.inferno
- nix/inferno-ml/tests/scripts/ones.inferno
Two large changes:
- The `ScriptMetadata` now contains the model IDs, which are mapped to their identifiers. The `InferenceParam` type no longer contains the models. Each entry in the map should correspond to a row in a junction table between models and scripts (note that this is done elsewhere) 
- The `ML.loadModel` primitive has been changed to take a `modelName` which are provided to the script evaluator. This is similar to how all of the bridge primitives work (i.e. only an identifier is provided directly by the user, which is resolved by the script evaluator). The old behavior is still available under `ML.unsafeLoadScript`, which just takes a filepath. The advantage of this is that `loadModel` can only be used with names known to be valid -- the correct filepath is derived for the …
> [inferno-ml] Map model idents to IDs in script metadata

- inferno-ml-server-types/CHANGELOG.md
- inferno-ml-server-types/inferno-ml-server-types.cabal
- inferno-ml-server-types/src/Inferno/ML/Server/Types.hs
Adds `Arbitrary` and `ToADTArbitrary` instances for most types in `inferno-ml-server-types`
Also simplifies `ModelMetadata`
> [inferno-ml] Add arbitrary instances

- inferno-vc/CHANGELOG.md
- inferno-vc/inferno-vc.cabal
- inferno-vc/src/Inferno/VersionControl/Client/Cached.hs
This avoids concurrent requests for the same object which is causing the thundering herd problem when several requests for the same object are DOSing inferno-vc
> [inferno-vc] Modify cached client so fetches for remote objects are serialized

- inferno-ml-server-types/src/Inferno/ML/Server/Types.hs
- inferno-ml-server/src/Inferno/ML/Server/Types.hs
- inferno-ml-server/test/Main.hs
- nix/default.nix
- nix/inferno-ml/migrations/v1-create-tables.sql
- nix/inferno-ml/tests/server.nix
Includes several changes to the `Model` and related types:
- Model permissions are now expressed as a single group ID (which simplifies things considerably)
- Models now contain `visibility` and `updated` fields, similar to Inferno VC scripts
- Some smaller changes to `ModelVersion` (adding a high-level description, etc...)
- Removal of `users` table, which isn't necessary
Since we don't need to support GHC 8 any longer, I've switched to using `-XOverloadedRecordDot` in some places. I'm going to remove GHC 8 support entirely when I finish the compiler upgrade (blocked on NVIDIA pain at the moment).
> [inferno-ml] Simplify model permissions, add more metadata

- inferno-vc/CHANGELOG.md
- inferno-vc/inferno-vc.cabal
- inferno-vc/src/Inferno/VersionControl/Server.hs
We had a `threadDelay` to perform cleanup every hour and the number of usecs was overflowing on 32 bit arch causing 100% CPU load
> [inferno-vc-server] Use unbounded-delays for threadDelay so it doesn't overflow on armv7l

- inferno-ml-server/CHANGELOG.md
- inferno-ml-server/inferno-ml-server.cabal
- inferno-ml-server/src/Inferno/ML/Server/Types.hs
- nix/inferno-ml/migrations/v1-create-tables.sql
Currently some entity IDs (group/user IDs) may overflow. So this changes the column type to a `numeric` to fix that
> [inferno-ml] Fix precision for entity ID columns

- inferno-vc/CHANGELOG.md
- inferno-vc/inferno-vc.cabal
- inferno-vc/src/Inferno/VersionControl/Client/Cached.hs
- inferno-vc/src/Inferno/VersionControl/Log.hs
- inferno-vc/src/Inferno/VersionControl/Operations/Filesystem.hs
- inferno-vc/src/Inferno/VersionControl/Server.hs
- inferno-vc/src/Inferno/VersionControl/Testing.hs
Made fetchObjectClosureHashes return the root scriptId because it belongs to the closure and so it is coherent with fetchObjectClosure. This makes the cached client take a lock on the requested scriptHash too when fetching the object which it wasn't doing before.
Also added logging to cached client to see hits/missed and to server to see which scriptIds are being used to call fetchObjects and fetchObjectClosureHashes
> [inferno-vc] Made fetchObjectClosureHashes return the root scriptId and added logging to cached client and server

- inferno-vc/CHANGELOG.md
- inferno-vc/inferno-vc.cabal
- inferno-vc/src/Inferno/VersionControl/Client/Cached.hs
- inferno-vc/src/Inferno/VersionControl/Log.hs
- inferno-vc/src/Inferno/VersionControl/Operations/Filesystem.hs
- inferno-vc/src/Inferno/VersionControl/Server.hs
- inferno-vc/src/Inferno/VersionControl/Testing.hs
Second take of #137. This version:
- removes emojis from log messages so `LANG` env var doesn't need  to be set to a UTF8 compatible one
- Changes the directory where closure hashes are cached to `deps-v2` so we don't read previously cached deps without the root scriptId
> [inferno-vc] Made fetchObjectClosureHashes return the root scriptId and added logging to cached client and server (take 2)

- inferno-vc/CHANGELOG.md
- inferno-vc/inferno-vc.cabal
- inferno-vc/src/Inferno/VersionControl/Client/Cached.hs
- inferno-vc/src/Inferno/VersionControl/Log.hs
- inferno-vc/src/Inferno/VersionControl/Operations/Filesystem.hs
- inferno-vc/src/Inferno/VersionControl/Server.hs
- inferno-vc/src/Inferno/VersionControl/Testing.hs
Reverts plow-technologies/inferno#139
> Revert "[inferno-vc] Made fetchObjectClosureHashes return the root scriptId and added logging to cached client and server (take 2)"

- inferno-vc/CHANGELOG.md
- inferno-vc/inferno-vc.cabal
- inferno-vc/src/Inferno/VersionControl/Client/Cached.hs
- inferno-vc/src/Inferno/VersionControl/Log.hs
- inferno-vc/src/Inferno/VersionControl/Server.hs
This PR adds logging to cached client to see hits/misses and makes the thundering-herd-prevention locks more granular while only taking the lock when actually fetching upstream. Also does some cleanup in that module so the thundering-herd-prevention logic is easier to inspect and functions have names that better describe what they do. This is 3rd take of #139 but this time the semantics of fetchVCObjectClosureHashes is not modified
> [inferno-vc] Cached client and server logging. More granular cache locks. Cleanup

- inferno-ml-server-types/CHANGELOG.md
- inferno-ml-server-types/inferno-ml-server-types.cabal
- inferno-ml-server-types/src/Inferno/ML/Server/Client.hs
- inferno-ml-server-types/src/Inferno/ML/Server/Types.hs
- inferno-ml-server/CHANGELOG.md
- inferno-ml-server/exe/ParseAndSave.hs
- inferno-ml-server/inferno-ml-server.cabal
- inferno-ml-server/src/Inferno/ML/Server.hs
- inferno-ml-server/src/Inferno/ML/Server/Bridge.hs
- inferno-ml-server/src/Inferno/ML/Server/Inference.hs
- inferno-ml-server/src/Inferno/ML/Server/Log.hs
- inferno-ml-server/src/Inferno/ML/Server/Types.hs
- inferno-ml-server/test/Client.hs
- inferno-ml-server/test/Main.hs
- inferno-ml/inferno-ml.cabal
- inferno-ml/src/Inferno/ML/Module/Prelude.hs
- nix/inferno-ml/migrations/v1-create-tables.sql
- nix/inferno-ml/tests/server.nix
Several improvements to `inferno-ml-server` (and its types package):
- Adds a new testing route with ability to override scripts, models, inputs
- Purges last vestiges of user IDs (now everything uses group IDs)
- Switches to UUIDs instead of integers for IDs
- Makes `/status` much clearer
- Removes some unnecessary parts of model caching; model versions are now saved to a filepath corresponding to their ID
> [inferno-ml] New testing route and other improvements

- inferno-ml-server-types/CHANGELOG.md
- inferno-ml-server-types/inferno-ml-server-types.cabal
- inferno-ml-server-types/src/Inferno/ML/Server/Client.hs
- inferno-ml-server-types/src/Inferno/ML/Server/Types.hs
- inferno-ml-server/exe/ParseAndSave.hs
- inferno-ml-server/src/Inferno/ML/Server/Inference.hs
- inferno-ml-server/src/Inferno/ML/Server/Types.hs
- nix/inferno-ml/migrations/v1-create-tables.sql
- nix/inferno-ml/tests/scripts/contrived.inferno
- nix/inferno-ml/tests/scripts/mnist.inferno
- nix/inferno-ml/tests/scripts/ones.inferno
- nix/inferno-ml/tests/server.nix
The previous way that parameter inputs/outputs were stored, with both condensed into a single `Map Ident ...`, turned out to be quite nightmarish to work with. We are going to be doing things like filtering or querying parameters by output, so we need it to be easier to look outputs up. So this changes the inputs/outputs back to the way they used to be, e.g. two separate `Map`s
> [inferno-ml] Change parameter input/output representation

- inferno-ml-server-types/CHANGELOG.md
- inferno-ml-server-types/inferno-ml-server-types.cabal
- inferno-ml-server-types/src/Inferno/ML/Server/Types.hs
- inferno-ml-server/CHANGELOG.md
- inferno-ml-server/inferno-ml-server.cabal
- nix/inferno-ml/migrations/v1-create-tables.sql
Now the database will record when models and their individual versions are saved
> [inferno-ml] Add creation date to models and model versions

- inferno-ml-server/CHANGELOG.md
- inferno-ml-server/inferno-ml-server.cabal
- inferno-ml-server/src/Inferno/ML/Server.hs
- inferno-ml-server/src/Inferno/ML/Server/Inference/Model.hs
- inferno-ml-server/src/Inferno/ML/Server/Types.hs
- inferno-ml-server/src/Inferno/ML/Server/Utils.hs
Currently, the entire server runs within `withConnect` and holds a single `Connection` within its `Env`. If Postgres is unreachable for some reason when the server starts, the process will hang until it's killed by an exception (which takes quite some time). If the connection fails while the server is running, the entire process will be brought down. This switches the server to use a `Pool` from `resource-pool` instead to create/hold connections on demand
> [inferno-ml] Use connection pool

- nix/inferno-ml/images/common/cpu.nix
- nix/inferno-ml/images/common/gpu.nix
- nix/inferno-ml/images/default.nix
- nix/inferno-ml/images/qcow2.nix
- nix/inferno-ml/modules/inferno-ml-server.nix
- nix/inferno-ml/tests/server.nix
Currently `inferno-ml-server.service` runs as a systemd user service. However, this doesn't actually work when testing the EC2 instances, as a shell must be opened for the `inferno` user before the service starts. We need it to start immediately after init
I've tested this with a real EC2 built using a testing image config and it fixes the problem
NOTE: We should eventually create an `inferno-ml-server` system user to run the service. However, for debugging and permissions purposes, it's easier to continue to run it as `inferno` for now. I've made an issue to fix this: https://github.com/plow-technologies/inferno/issues/151. But this fix is needed urgently and I don't want to hold things up fixing that.
> [inferno-ml] Move `inferno-ml-server` to system service

- inferno-types/CHANGELOG.md
- inferno-types/inferno-types.cabal
- inferno-types/src/Inferno/Types/VersionControl.hs
This makes vcHash for VCMeta produce the same hash on 32bit and 64 bit plarforms
> Make VCHashUpdate @CTime always encode as 64 bits

- inferno-ml-server/src/Inferno/ML/Server/Inference.hs
Currently, if a script has no models attached to it, trying to get the param will result in a very misleading `Parameter ... does not exist` error response. This fixes the SQL query to return a default empty model object if there are no models attached to the script.
> [inferno-ml] Fix query to allow for scripts without models

- flake.lock
- flake.nix
- nix/default.nix
- nix/legacy-packages.nix
- nix/nixos-modules.nix
Bumps haskell.nix flake input to a slightly newer commit than in #159 so that we can use 24.11 as a new stable branch. Also adds a few small changes (adding `hlint` to the shell env, etc...).
The new nixpkgs for building images is working (I've confirmed elsewhere).
No Haskell changes.
> [nix] Bump haskell.nix and nixpkgs again

- inferno-ml/CHANGELOG.md
- inferno-ml/inferno-ml.cabal
- inferno-ml/src/Inferno/ML/Module/Prelude.hs
Currently, `toDevice` takes a user-supplied `Text` as the name of the device to move the tensor. This is not ideal since it's easy to make a mistake and get some nasty Torch error. This changes `toDevice` to take a `{#cpu,#cuda}` enum as an argument and renames the existing primitive to `toDeviceUnsafe`
> [inferno-ml] Fix `toDevice` primitive

- cabal.project
- nix/default.nix
- nix/modules.nix
The recent GHC/nixpkgs upgrade broke using `cabal repl`, so this fixes it:
- adds `nonReinstallablePkgs` back
- exports `CPLUS_INCLUDE_PATH` so that `libtorch-ffi` can find the `libtorch` headers in ghci sessions
> [inferno-ml] Re-add `nonReinstallablePkgs` and fix `inferno-ml` shell environment

- inferno-ml-server-types/CHANGELOG.md
- inferno-ml-server-types/inferno-ml-server-types.cabal
- inferno-ml-server-types/src/Inferno/ML/Server/Types.hs
- inferno-ml-server/CHANGELOG.md
- inferno-ml-server/inferno-ml-server.cabal
- inferno-ml-server/src/Inferno/ML/Server.hs
- inferno-ml-server/src/Inferno/ML/Server/Bridge.hs
- inferno-ml-server/src/Inferno/ML/Server/Inference.hs
- inferno-ml-server/src/Inferno/ML/Server/Log.hs
- inferno-ml-server/src/Inferno/ML/Server/Types.hs
- inferno-ml-server/src/Inferno/ML/Server/Utils.hs
- nix/inferno-ml/images/common/cpu.nix
- nix/inferno-ml/images/common/gpu.nix
- nix/inferno-ml/images/common/qcow2.nix
- nix/inferno-ml/migrations/v1-create-tables.sql
- nix/inferno-ml/modules/inferno-ml-server.nix
- nix/inferno-ml/tests/server.nix
If the `instanceId` field is present in the config, inferno-ml-server will persist error traces in the database.
> [inferno-ml-server] Persistent traces

- inferno-ml/CHANGELOG.md
- inferno-ml/inferno-ml.cabal
- inferno-ml/src/Inferno/ML/Module/Prelude.hs
Similar to other issues we've had in the past, Hasktorch's `forward` is presented as a "pure" function but actually uses `unsafePerformIO` internally. This leads to use not catching `CppException`s in case the Torch interpreter runs into a problem. This fixes the primitive by using `evaluate` to lift Hasktorch's `forward` into `IO` and then catching/rethrowing the exception as an Inferno `EvalError`. `inferno-ml-server` should then send a proper error response in case of an exception.
I've run this against both sets of Inferno ML integration tests that we have an it works with existing (good) scripts. I also tried running some known-bad Torchscript `ScriptModules` and the exception is caught.
> [inferno-ml] Fix `forward` primitive

- inferno-ml-server-types/CHANGELOG.md
- inferno-ml-server-types/inferno-ml-server-types.cabal
- inferno-ml-server-types/src/Inferno/ML/Server/Types.hs
- inferno-ml-server/CHANGELOG.md
- inferno-ml-server/inferno-ml-server.cabal
- inferno-ml-server/src/Inferno/ML/Server.hs
- inferno-ml-server/src/Inferno/ML/Server/Inference.hs
- inferno-ml-server/src/Inferno/ML/Server/Inference/Model.hs
- inferno-ml-server/src/Inferno/ML/Server/Log.hs
- inferno-ml-server/src/Inferno/ML/Server/Utils.hs
- inferno-ml-server/test/Main.hs
- nix/inferno-ml/migrations/v1-create-tables.sql
- nix/inferno-ml/tests/server.nix
Since the `contents` of a `ModelVersion` are immutable, we can calculate its size once and store it in the DB. Currently we only need the size once in `inferno-ml-server` (when caching a model version) but now we want to display them elsewhere. Calculating it each time is wasteful.
This also includes a few other changes:
- `SqlError`s are now caught and rethrown so they show up as error traces and in error responses 
- The `unique` constraint on `models` has been changed so that a new model can be created with the same name as (a) previously terminated model(s)
> [inferno-ml] Store model version size

- inferno-ml-server-types/CHANGELOG.md
- inferno-ml-server-types/inferno-ml-server-types.cabal
- inferno-ml-server-types/src/Inferno/ML/Server/Types.hs
- inferno-ml-server/CHANGELOG.md
- inferno-ml-server/inferno-ml-server.cabal
- inferno-ml-server/src/Inferno/ML/Server/Inference.hs
- inferno-ml-server/src/Inferno/ML/Server/Module/Bridge.hs
- inferno-ml-server/src/Inferno/ML/Server/Module/Types.hs
- inferno-ml/CHANGELOG.md
- inferno-ml/inferno-ml.cabal
- inferno-ml/src/Inferno/ML/Module/Prelude.hs
- Makes `Writes` stream take any `IValue` (previously it was restricted to doubles only)
- Expands `IValue` to take more Inferno `Value` types (required for full range of possible writes)
- Changes Aeson instances accordingly (not as compact as before, but that's unavoidable)
- Adds `unsqueeze` primitive (tiny change so included it here)
> [inferno-ml] Allow non-double `Writes` and more value types

- inferno-ml-server-types/CHANGELOG.md
- inferno-ml-server-types/inferno-ml-server-types.cabal
- inferno-ml-server-types/src/Inferno/ML/Server/Types.hs
- inferno-ml-server/CHANGELOG.md
- inferno-ml-server/inferno-ml-server.cabal
- inferno-ml-server/src/Inferno/ML/Server/Inference.hs
- inferno-ml-server/src/Inferno/ML/Server/Types.hs
- inferno-ml-server/src/Inferno/ML/Server/Utils.hs
- nix/inferno-ml/migrations/v1-create-tables.sql
Just a bit of cleanup, mostly SQL things. Some tables had foreign keys that could also serve as primary keys, and I made the primary key of `scripts` more reasonable/idiomatic (along with necessary changes on the Haskell side).
Also adds the script hash to the server's `InfernoError`.
> [inferno-ml] Some SQL and error cleanup

- cabal.project
- inferno-ml-compat/CHANGELOG.md
- inferno-ml-compat/hie.yaml
- inferno-ml-compat/inferno-ml-compat.cabal
- inferno-ml-compat/src/Inferno/ML/Compat/Module/Prelude.hs
- inferno-ml-compat/src/Inferno/ML/Compat/Types/Value.hs
- inferno-ml-compat/src/Inferno/ML/Module/Compat.hs
- inferno-ml-compat/src/Inferno/ML/Types/Value/Compat.hs
- inferno-ml-server/CHANGELOG.md
- inferno-ml-server/exe/ParseAndSave.hs
- inferno-ml-server/inferno-ml-server.cabal
- inferno-ml-server/src/Inferno/ML/Server/Bridge.hs
- inferno-ml-server/src/Inferno/ML/Server/Inference.hs
- inferno-ml-server/src/Inferno/ML/Server/Module/Prelude.hs
- inferno-ml-server/src/Inferno/ML/Server/Module/Types.hs
- inferno-ml/CHANGELOG.md
- inferno-ml/app/Main.hs
- inferno-ml/inferno-ml.cabal
- inferno-ml/lsp/Main.hs
- inferno-ml/src/Inferno/ML/Module/Prelude.hs
- inferno-ml/src/Inferno/ML/Types/Value.hs
- inferno-ml/test/Spec.hs
Currently we have two places (here in `inferno` and elsewhere) where we need to use the `ML` module primitive definitions. The current `inferno-ml` package has a hard dependency on `hasktorch`, however, which we can't use in the other place we need the `ML` module, so we've had to duplicate the module definition and keep the two in sync manually.
This fixes that by adding an `inferno-ml-compat` package that, given certain types (tensor, script module, etc...), will generate the `ML` module from the primitives contained in a group of record-of-functions.
The `inferno-ml` package instantiates this using `Tensor`, `ScriptModule`, etc... from Hasktorch, and provides primitive implementations that can be evaluated at runtime. Elsewhere we can use dummy types for type-checking and LSP purposes. …
> [inferno-ml] Add `inferno-ml-compat` to generate `ML` module

- inferno-core/CHANGELOG.md
- inferno-core/inferno-core.cabal
- inferno-core/src/Inferno/Docs.hs
Adds `Inferno.Docs.mkPreludeDocs` to generate markdown docs for all primitives and typeclasses in the given prelude.
Example output (module docs from generating for `defaultMlPrelude`):
```md
`add t1 t2` adds each element of the tensor `t2` to each element of the
tensor `t1` and returns a new resulting tensor
----
`addScalar summand t` adds each element of `t` with the scalar `summand`
and returns a new resulting tensor
----
Returns true if all elements in the tensor are true, false otherwise
----
`allDim dim keepdim t` returns true if all elements in each row of `t`
in the given dimension `dim` are true, false otherwise. If `keepdim` is `#true`,
the output tensor is of the same size as `t` except in the dimension `dim` where
it is of size 1. Otherwise, `dim` is squeezed, resulting in the …
```
> Add function to generate prelude docs

- inferno-ml-server-types/CHANGELOG.md
- inferno-ml-server-types/inferno-ml-server-types.cabal
- inferno-ml-server-types/src/Inferno/ML/Server/Types.hs
- inferno-ml-server/CHANGELOG.md
- inferno-ml-server/inferno-ml-server.cabal
- inferno-ml-server/src/Inferno/ML/Server.hs
- inferno-ml-server/src/Inferno/ML/Server/Log.hs
- inferno-ml-server/src/Inferno/ML/Server/Types.hs
- inferno-ml-server/src/Inferno/ML/Server/Utils.hs
- nix/inferno-ml/modules/inferno-ml-server.nix
- Adds an `OOMPolicy` for the `inferno-ml-server` process with `MemoryMax` as a percentage of system memory
- Adds warning logs if the server is restarting from an OOM event (helpful for debugging)
- Adds `configuration.memoryMax` to the NixOS config for the server with corresponding adjustments on the Haskell type
This is needed because scripts can sometimes consume all system memory until kernel memory reclamation begins and the entire system slows to a crawl and freezes from a user's point of view. It's better to just kill the process and restart it in this case, otherwise we can't even e.g. poll the process status. A subsequent PR will add in-process memory monitoring to preempt the OOM and just kill the thread that's evaluating the script, but that's a different task (and requires …
> [inferno-ml] Run `inferno-ml-server` within systemd OOM policy

- inferno-core/CHANGELOG.md
- inferno-core/inferno-core.cabal
- inferno-core/src/Inferno/Module/Prelude.hs
- inferno-core/src/Inferno/Module/Prelude/Defs.hs
- inferno-core/test/Eval/Spec.hs
Adds a wrapper around `Data.Time.Format.parseTimeM` so we can parse text inputs into `option of time`s with a user-provided format string.
> [inferno-core] Add `Time.parseTime`

- inferno-ml-server-types/CHANGELOG.md
- inferno-ml-server-types/inferno-ml-server-types.cabal
- inferno-ml-server-types/src/Inferno/ML/Server/Types.hs
- inferno-ml-server/CHANGELOG.md
- inferno-ml-server/inferno-ml-server.cabal
- inferno-ml-server/src/Inferno/ML/Server.hs
- inferno-ml-server/src/Inferno/ML/Server/Inference.hs
- inferno-ml-server/src/Inferno/ML/Server/Log.hs
- inferno-ml-server/src/Inferno/ML/Server/Types.hs
- inferno-ml-server/src/Inferno/ML/Server/Utils.hs
Adds an in-process monitor for memory usage during script evaluation by reading the cgroup memory information for the `inferno-ml-server` systemd service. If we get close to the OOM threshold, the server will respond with an error message and then restart itself. This avoids having script evaluation interrupted **without** an error message, which is the case currently. Since we have `Restart=always` defined for the systemd service, the process memory is freed and the service restarts.
At first I wanted to avoid having the restart, but despite my best efforts I could not get GHC or libc arenas (from Torch FFI) to free enough memory. That would leave us in a state where memory was still allocated but not freed, and any subsequent script evaluations would fail. We would still get the error …
> [inferno-ml] Add in-process memory monitor to preempt systemd OOM
